# 2021120044_김형겸_hw1_1

## 02_1

In [6]:
import torch

In [8]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)  
print(t1.requires_grad)  
print(t1.size())  
print(t1.shape)   
t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


__torch.Tensor == torch.FloatTensor__


torch.tensor는 입력 받은 자료형 그대로 tensor화


tensor화하면 동일 객체로 사용하는 것이 아닌 새로운객체를 copy해서 tensor화 함
>np.array를 torch.as_tensor를 이용할 경우에는 동일 객체를 사용하여 값이 이후에 변경될 수 있다


torch.Tensor   
>tensor 자료구조 클래스 인스턴스 생성
   
device='cpu'   
>CPU에 배치
   
t1.dtype   
>t1의 데이터 유형
  
t1.device
>t1의 장치 정보

t1.size
>t1의 크기

t1.shape
>t1의 모양

t1.cpu
>t1을 cpu로 복사하여 새로운 tensor 생성 기존 텐서를 다른 장치로 이동하거나 복사할 때 사용

***

In [9]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  
print(t2.device) 
print(t2.requires_grad)  
print(t2.size())  
print(t2.shape)  
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


torch.tensor
>어떠한 데이터를 tensor로 copy 해준다, 데이터가 tensor가 아니면 Tensor클래스를 적용하여 복사

***

In [10]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

.ndim
>tensor의 깊이


마지막 a11처럼 한번의 하나의 값으로 표현 못하게 생성 불가


__추가 팁 : shape을 구할 때 좌측 [을 기준으로 하나씩 소거해가며 구하면 쉽게 구할 수 있다__
***

## 02_2

In [2]:
import torch
import numpy as np

In [4]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


torch.Tensor
>int 입력 시 float로 변환
>
>
>Tensor 객체로 입력 받은 메모리 공간을 그대로 사용
>
>
>list나 numpy로 입력 받은 값을 복사하여 Tensor 객체 생성

torch.tensor
>int 입력 시 int 그대로
>
>
>입력 받은 데이터를 새로운 메모리 공간에 복사해 Tensor 객체 생성

torch.as_tensor
>default값으로 데이터 유형 및 장치 설정 유지
>
>
>list일 때 값 복사해서 사용


위 3가지 방법 모두 기존 값을 그대로 사용하는 것이 아닌 새로운 값이라는 것을 알 수 있다
***

In [13]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


torch.as_tensor
>array일 때 값을 복사하지 않고 그대로 사용
***

## 2_3

In [14]:
import torch

In [15]:
t1 = torch.ones(size=(5,))  
t1_like = torch.ones_like(input=t1)
print(t1)  
print(t1_like) 

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


torch.ones(size=(5,))
torch.ones(5)
>요소가 1인 사이즈가 5인 tensor 생성

torch.ones_like(input=t1)
>주어진 입력 tensor와 동일한 모양 및 데이터 유형을 가지지만 모든 요소가 1인 tensor 생성

***

In [16]:
t2 = torch.zeros(size=(6,)) 
t2_like = torch.zeros_like(input=t2)
print(t2)  
print(t2_like) 

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


torch.zeros(size=(6,))
torch.zeros(6)
>요소가 0인 사이즈가 6인 tensor 생성

torch.zeros_like(input=t2)
>주어진 입력 tensor와 동일한 모양 및 데이터 유형을 가지지만 모든 요소가 0인 tensor 생성

***

In [17]:
t3 = torch.empty(size=(4,))  
t3_like = torch.empty_like(input=t3)
print(t3)  
print(t3_like)  

tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


torch.empty(size=(4,))

>초기화 되지 않은 size 4의 tensor 반환

torch.empty_like(input=t3)
>input과 같은크기의 초기화되지 않은 텐서 반환

***

In [18]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


torch.eye(n=3)
>[n,n]짜리 단위 행렬 생성

***

## 2_4

In [19]:
import torch

In [5]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

tensor([[15, 13]])
tensor([[0.6162, 0.3214, 0.4610]])
tensor([[-0.4597, -0.1294, -0.8072]])
tensor([[ 9.9249, 10.2503],
        [ 9.7428,  9.6079],
        [10.5029,  8.6182]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


torch.randint(low=10, high=20, size=(1, 2))
>[10, 20)의 요소를 가지는 [1, 2] tensor 생성
>
>
>torch.randint(low=0, high, size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

t2 = torch.rand(size=(1, 3))
>[0, 1)의 요소를 가지는 [1, 3] tensor 생성
>
>
>torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

torch.randn(size=(1, 3))
>평균 0, 분산 1의 정규 분포에서 요소를 가지는 [1, 3] tensor 생성
>
>
>torch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
>10의 평균을 가지는 1의 표준편차에서 요소를 가지는 [3, 2] tensor 생성
>
>
>torch.normal(mean, std, *, generator=None, out=None)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
>0부터 5까지의 균등한 간격을 가지는 3개의 요소를 가지는 tensor 생성
>
>
>torch.linspace(start, end, steps, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

t6 = torch.arange(5)
>[0, 5)에서 1의 간격을 가지는 tensor 생성
>
>
>torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
***

In [21]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


torch.manual_seed(1729)
>난수 생성을 위한 시드 설정
>
>
>torch.Generator 객체 반환
***

## 2_5

In [22]:
import torch

In [23]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


torch.ones((2, 3))
>ones default dtype = float32

torch.ones((2, 3), dtype=torch.int16)
>dtype int16 ones

torch.rand((2, 3), dtype=torch.float64) * 20.
>dtype float64 rand 값에 *20.

b.to(torch.int32)
>b tensor int32로 생성
***

In [11]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16


torch.ones(10, 2, dtype=torch.double)
torch.zeros(10, 2).double()
torch.zeros(10, 2).to(torch.double)
torch.zeros(10, 2).type(torch.double)
>dtype = float64(double)

torch.tensor([[1, 2]], dtype=torch.short)
torch.ones(10, 2).short()
torch.ones(10, 2).to(dtype=torch.short)
torch.ones(10, 2). type(dtype=torch.short)
>dtype = int16(short)
***

In [25]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


__다른 언어와 마찬가지로 바이트가 큰 크기에 타입에 맞추어짐__

## 2_6

In [26]:
import torch

In [27]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


torch.add(t1, t2), t1 + t2
>shape이 같음, 각각의 위치끼리 값 더해 tensor 생성
>
>
>torch.add(input, other, *, out=None)
***

In [28]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.sub(t1, t2), t1 - t2
>shape이 같음, 각각의 위치에서 t1의 요소에서 t2의 요소를 뻄
>
>
>torch.sub(input, other, *, alpha=1, out=None)
***

In [29]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.mul(t1, t2), t1 * t2
>shape이 같음, 각각의 위치에서 값을 곱해 tensor 생성
>
>
>torch.mul(input, other, *, out=None)
***

In [30]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.div(t1, t2), t1 / t2
>shape이 같음, 각각의 위치에서 t1의 요소에서 t2의 요소를 나눔
>
>
>torch.div(input, other, *, rounding_mode=None, out=None)
***

## 2_7

In [1]:
import torch

In [4]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[0.1329, 1.9337],
        [0.9776, 1.2158]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


torch.dot
>두 텐서의 도트 곱을 계산하는데 사용, 요소 수가 같은 두 개의 1D 텐서의 도트 곱만 계산 가능
>
>
>torch.dot(input, other, *, out=None)

torch.mm(t2, t3)
>t2, t3의 행렬 곱셈 수행
>
>
>torch.mm(input, mat2, *, out=None)
>
>
>input(n*m), mat2(m*p), oup(n*p)

torch.bmm(t5, t6)
>b개의 행렬 곱셈 수행
>
>
>torch.bmm(input, mat2, *, deterministic=False, out=None)
>
>
>input(b*n*m), mat2(b*m*p), oup(b*n*p)

## 2_8

In [17]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(t1)
print(t2)
print(torch.matmul(t1, t2))
print(torch.matmul(t1, t2).size(), "!") 

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(t3)
print(t4)
print(torch.matmul(t3, t4))
print(torch.matmul(t3, t4).size(), "!!") 
t4 = torch.randn(3)
print(t4)
print(torch.matmul(t4, t3))
print(torch.matmul(t4, t3).size(), "!!")

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(t5)
print(t6)
print(torch.matmul(t5, t6))
print(torch.matmul(t5, t6).size(), "!!!")

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(t7)
print(t8)
print(torch.matmul(t7, t8))
print(torch.matmul(t7, t8).size(), "!!!!")

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(t9)
print(t10)
print(torch.matmul(t9, t10))
print(torch.matmul(t9, t10).size(), "!!!!!") 

tensor([-0.3399, -1.4125,  1.1066])
tensor([ 1.8106, -1.3298, -1.5758])
tensor(-0.4808)
torch.Size([]) !
tensor([[-0.3648, -0.2919, -0.2613, -0.5564],
        [-1.5579,  0.6375, -0.7622,  1.3913],
        [ 0.9190,  0.0926,  0.7709,  0.3425]])
tensor([ 0.1820, -0.7398,  0.6576,  0.5444])
tensor([-0.3252, -0.4989,  0.7921])
torch.Size([3]) !!
tensor([ 0.0423,  0.6298, -0.6318])
tensor([-1.5772,  0.3306, -0.9781,  0.6362])
torch.Size([4]) !!
tensor([[[ 0.9046, -1.3521,  0.7784,  0.0410],
         [ 0.2024, -1.7127,  0.3070, -0.6011],
         [ 0.7466, -0.5190, -1.0383,  2.0450]],

        [[-0.2236,  0.8599, -2.3212, -0.1385],
         [ 0.8465,  0.5619, -0.0510, -1.3666],
         [ 0.3746, -1.6600, -0.4449,  0.9988]],

        [[-0.6811, -0.9588,  1.0690,  0.6095],
         [-0.6558,  0.4717, -0.3714, -0.3376],
         [ 0.4453, -0.8635,  1.0695,  0.5943]],

        [[-1.9282, -0.0222, -1.0411,  1.1112],
         [-0.0609,  0.9552, -0.3780,  0.2547],
         [-1.0540,  0.2499, -0.03

torch.matmul
>두 tensor의 행렬 곱으로 아래와 같이 tensor의 차원에 따라 수행 방식이 달라짐
>>모두 1차원일 경우 도트 곱
>
>
>>2차원일 경우 행렬 곱
>
>
>>첫번째 인자 1차원, 두번째 인자 2차원일 경우 첫번째 인자에 1차원이 추가되고 행렬곱셈 후 차원 제거
>
>
>>첫번째 인자 2차원, 두번째 인자 1차원일 경우 broadcasted dot 계산
>
>
>>n차원, n차원 일 경우
>>>input(k*n*m), other(k*m*t), out(k*n*t)
>>
>>
>>>input(j*1*n*n), other(k*n*n), out(j*k*n*n)
>>
>>
>>>input(j*1*n*n), other(k*m*p), out(j*k*n*p)
>>
>>
>tor

>torch.matmul(input, other, *, out=None)
***

## 2_9

In [34]:
import torch

In [ ]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

t2의 값을 t1의 broadcasted 해서 곱

In [36]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


t4의 값을 t3의 broadcasted해서 차원에 맞춰 요소를 뺌

In [37]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0) 
print(t5 - 2.0) 
print(t5 * 2.0)  
print(t5 / 2.0)  

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


각 연산에 맞춰 스칼라 값을 tensor의 broadcasted해서 모든 요소에 연산해줌

In [20]:
def normalize(x):
  return x / 255

t6 = torch.randn(3, 28, 28)
print(t6)
print(normalize(t6).size())
print(normalize(t6))

tensor([[[ 0.1719, -0.2925,  0.3279,  ..., -0.0249, -1.4473,  0.2412],
         [ 0.6834, -1.0371, -0.2216,  ..., -0.8588, -0.5963,  1.0098],
         [-0.2098,  0.5969,  1.7913,  ..., -0.8927, -0.2805,  0.7293],
         ...,
         [ 0.0121,  0.8591, -0.2644,  ..., -0.4610,  1.2765,  0.8202],
         [ 0.1559,  0.6365,  1.0746,  ..., -0.3005, -0.4773,  0.9754],
         [ 1.2047, -0.5631,  2.9064,  ...,  1.5419, -0.0440, -2.9189]],

        [[-0.6450, -1.4451, -0.7492,  ...,  0.5988, -0.3920,  1.0211],
         [-0.1843, -1.0505, -2.1471,  ..., -0.7087, -0.1565, -0.0987],
         [-1.5852,  0.8719,  0.4008,  ...,  0.4100, -0.1276,  1.3463],
         ...,
         [-2.2456, -0.8266,  1.1859,  ...,  1.0109,  0.4998,  0.4500],
         [-1.8382, -1.1656, -0.8066,  ..., -0.7669, -0.2664, -0.8339],
         [ 1.0981,  0.9372, -0.8587,  ..., -0.6134, -0.2306, -1.4975]],

        [[ 0.4936, -0.1543,  0.3230,  ...,  0.2653, -1.1500,  0.2543],
         [ 1.1746,  1.5592,  0.4177,  ...,  1

함수도 broadcasted 되는 것을 볼 수 있음

In [39]:
t7 = torch.tensor([[1, 2], [0, 3]]) 
t8 = torch.tensor([[3, 1]])  
t9 = torch.tensor([[5], [2]])  
t10 = torch.tensor([7]) 
print(t7 + t8)  
print(t7 + t9)   
print(t8 + t9)  
print(t7 + t10)  

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


broadcasted가 가능하려면 한쪽에 차원이 다른 차원의 배수의 형태이면 가능

In [40]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2) 
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1) 
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  
print((t17 + t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


tensor의 차원의 dim이 다르더라도 한쪽에 차원을 추가하여 만들 수 있다면 broadcasted 가능

In [29]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size(), "v1") 

t19 = torch.empty(5, 3, 4, 2)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size(), "v2") 

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 7)
print((t19 + t20).size(), "v3") 

# t19 = torch.empty(5, 6, 4, 1)
# t20 = torch.empty(3, 1, 7)
# print((t19 + t20).size(), "v4") 

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size()) 

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size()) 

torch.Size([5, 3, 4, 1]) v1
torch.Size([5, 3, 4, 2]) v2
torch.Size([5, 3, 4, 7]) v3
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


broadcasting은 같은 차원의 크기가 한쪽이 1이거나 차원이 동일하여야 가능
>v1, v2, v3은 가능하고 v4는 불가능

In [43]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


torch.pow(t27, 2)
>차원의 크기가 한쪽이 1일 경우
>
>
>>각 요소의 1인 차원의 값 연산 수행

torch.pow(a, exp)
>차원의 크기가 동일할 경우
>
>
>>각 요소별로 연산 수행
***

## 2_10

In [44]:
import torch

In [45]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  
print(x[:, 1])  
print(x[1, 2]) 
print(x[:, -1]) 
print(x[1:])
print(x[1:, 3:]) 

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


파이썬의 리스트에서 주로 사용되는 슬라이스를 tensor에서도 사용 가능


,의 순서대로 좌측부터 dim 0이라고 생각하고 :의 좌측이 시작위치 우측이 종료 위치
>:만 사용 될 경우 all
>
>
>우측의 경우 해당 위치까지는 안들어감 -1 위치까지만 적용됨
>
>
>> x:y == [x, y)

In [47]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [48]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## 2_11

In [49]:
import torch

In [50]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  
t3 = t1.reshape(1, 6)  
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  
t5 = torch.arange(6).view(2, 3) 
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


t1.view(3, 2)
>self tensor와 데이터는 같지만 shape이 다른 새 텐서 반환
>
>
>데이터를 공유하며 요소 수가 같아야 하지만 크기는 다를 수 있다


t1.reshape(1, 6)
>self와 데이터 및 요소 수는 동일하지만 지정된 모양을 가진 tensor 반환


view와 reshape의 차이
>view는 contiguous 속성을 만족하지 못할 경우 일부 사용이 제한됨


contiguous
>axis 순서대로 자료가 저장된 상태 true
>
>
>자료 저장 순서가 원래 방향과 어극난 경우 false


torch.arange(8).view(2, 4)
>arange와 view 동시 사용
***

In [51]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  

# Remove dimension at position 0
t8 = t6.squeeze(0)  
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


self.squeeze(dim)
>input의 dim의 차원의 크기가 1이면 해당 차원 제거
>
>
>만약 dim이 안주어지면 해당 tensor의 크기가 1인 차원 전부 제거


torch.squeeze(input, dim=None, *, out=None)

In [52]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


self.unsqueeze(dim)
>dim의 크기가 1인 차원 추가
>
>
>만약 해당 위치에 이미 차원이 있다면 해당 차원과 해당 차원-1 차원 사이의 차원 추가


torch.unsqueeze(input, dim)
***

In [53]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


torch.flatten
>input tensor를 1차원 텐서로 재형성


torch.flatten(input, start_dim=0, end_dim=-1)
***

In [54]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


torch.permute
>tensor의 shape변경 차원의 dim index로 변경
>
>
>동시에 여러개의 차원 변경 가능


torch.transpose
>input의 전치된 버전인 텐서 반환
>
>
>torch.transpose(input, dim0, dim1)
***

## 2_12

In [31]:
import torch

In [35]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4)
print(t4.shape)
t1 = torch.zeros([2, 1, 3])
t2 = torch.ones([2, 3, 3])
t3 = torch.rand([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4)
print(t4.shape)

t5 = torch.arange(0, 3)  
t6 = torch.arange(3, 8)  

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  
print(t7)  

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 6, 3])
tensor([[[0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [0.4833, 0.1801, 0.3354],
         [0.9461, 0.1084, 0.3837]],

        [[0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [0.8157, 0.4421, 0.0204],
         [0.8765, 0.0451, 0.7221]]])
torch.Size([2, 6, 3])
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


torch.cat
>주어진 차원을 연결
>
>
>모든 텐서는 동일한 모양이거나 비어 있어야 함
>
>
>torch.cat(tensors, dim=0, *, out=None)
***

In [58]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [59]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [60]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


차원을 합칠 때 tensor의 입력순으로 요소를 채우며 해당 차원의 크기를 더하고 tensor를 구성한다고 생각하면 쉽게 할 수 있다

## 2_13

In [61]:
import torch

In [62]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


torch.stack
>새로운 차원을 따라 tensor 연결
>
>
>모든 텐서의 크기는 동일해야 함
>
>
>torch.stack(tensors, dim=0, *, out=None)


self.equal
>self와 input의 tensor가 동일한지 확인
>
>
>torch.equal(input, other)
***

In [63]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


stack으로 합치는 과정을 cat 및 해당 차원을 unsqueeze로 증가시켜 동일하게 만들 수 있음

## 2_14

In [64]:
import torch

In [39]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t3)


t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t4.shape)
print(t5.shape)
print(t6.shape)
print(t6)

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)


t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)


t9 = torch.vstack([t7, t8])
print(t9.shape)


print(t9)

torch.Size([3])
torch.Size([3])
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([3, 1])
torch.Size([3, 1])
torch.Size([6, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


torch.vstack
>tensor를 세로로 순서대로 쌓음
>
>
>dim 0이 합쳐진다 생각, 만약 둘다 1차원일 경우 새로운 차원으로 합쳐짐 (t1, t2, t3)
>
>
>torch.vstack(tensors, *, out=None)
***

In [66]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


torch.hstack
>tensor를 가로 방향으로 순서대로 쌓음
>
>
>1차원 tensor의 경우 dim 0으로 연결하고 다른 모든 tensor는 dim 1 축으로 연결
>
>
>torch.hstack(tensors, *, out=None)
***

# 숙제 후기

tensor에 대해서 처음 배워보는 내용이라 걱정도 많았지만 새로운 것을 배운다는 것이 설레어 재미있게 진행하였다. tensor의 여러가지 함수들을 직접 사용해보며 각 사용법을 알게 되었고 내부적으로 어떤식으로 동작하는지 궁금하여 함수의 원형과 함께 여러자료들을 찾아보게 되었다.
지금 공부해본 내용도 많다고 생각되었는데 tensor와 관련된 라이브러리 함수들에 목록을 보며 배울것이 많이 남아 걱정이 많이 되었다.
수업 진행도 처음 배워보는 내용이라 걱정을 많이 하였는데 교수님께서 천천히 설명 해주시며 실제 계산하는 방식을 보여주시며 수업을 하셔서 이해가 잘 되었습니다.